[build]
  publish = "public"
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.68.3"

[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"
