[build]
  publish = "public"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "deploy-preview"
  command = "cd themes/docsy && git submodule update -f --init && npm install postcss-cli && cd ../.. && hugo"

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "production"
  command = "cd themes/docsy && git submodule update -f --init && npm install postcss-cli && cd ../.. && hugo"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.86.0"

