[build]
  publish = "public"
  command = "cd themes/docsy && git submodule update -f --init && npm install postcss-cli && hugo

[context.deploy-preview.environment]
  HUGO_VERSION = "0.86.0"

[context.production.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.86.0"


