[build]
  publish = "public"
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.85.1"

[context.production.environment]
  HUGO_VERSION = "0.85.1"
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.85.1"

